### ISSUE TITLE
Отключение MQTT

### ISSUE THREAD

**Issue by Frystail** [vvip-68/NodeMCU-MQTT-WS2812#2]
Здравствуйте. Как отключить в прошивке использование MQTT сервера, и WiFi. Нужно только циклическое повторение эффектов.

**Comment by vvip-68** [comment]
Вам лучше взять исходную прошивку от Alex Gyver, где нет управления через MQTT - только эффекты. Эта прошивка доработана СПЕЦИАЛЬНО для управления через MQTT сервер.
