### ISSUE TITLE
Сервис который предлагается в инструкции стал платным

### ISSUE THREAD

**Issue by FridayJew** [vvip-68/NodeMCU-MQTT-WS2812#8]
А как использовать другой я чет не допетрил. Многие что нахожу предлагают чисто адрес и порт , иногда даже без логина и пароля. Тоесть чисто теоретически его можно наверное было бы использовать , но как идентифицировать своё устройство на этом сервере не понятно.
Истина где то рядом.

**Comment by vvip-68** [comment]
Ну да, проект немножко подзаброшен... Что-то руки так и не дошли переделать его под бесплатный сервер... Сделаю со временем... Пока 2D гирляндой занят...
