### ISSUE TITLE
При компиляции ошибка: settings.h: No such file or directory

### ISSUE THREAD

**Issue by Tihon-laz** [vvip-68/NodeMCU-MQTT-WS2812#9]
Здравствуйте! Столкнулся с такой проблемой:

WS2812_FX_1.02:67:10: fatal error: settings.h: No such file or directory

Подскажите, пожалуйста, в чем может быть причина? Возможно ли как-то исправить?

**Comment by vvip-68** [comment]
Да, конечно. Для этого нужно прочитать комментарий тремя строчками выше той, где указывается ошибка в исходном коде скетча.

**Comment by Tihon-laz** [comment]
Спасибо большое! Не заметил...
